module Const
  WINDOW_SIZE = 300
  WINDOW_STEP = 25

  OTU_CUTOFF = 0.03

  SILVA_LEN = 50000

  ASSETS_FOLDER = File.join File.dirname(__FILE__), "assets"

  ENTROPY = File.join ASSETS_FOLDER, "entropy.db_no_outgroups.txt"

  HV_REGIONS = File.join ASSETS_FOLDER, "hv_regions.txt"

  DATABASE = File.join ASSETS_FOLDER, "database.fa"

  DE_DIST = File.join ASSETS_FOLDER, "database_DE_dist.txt"
  DE_DIST_PERCENTILES =
    File.join ASSETS_FOLDER, "database_DE_dist_percentiles.txt"

  NUM_PERCENTILES = 10

  RSCRIPT = File.join ASSETS_FOLDER, "pintail_plot.r"

  # not a user file, generated by the program
  FLAGGED_SEQS = File.join ASSETS_FOLDER, "queries.pintail_flagged.txt"

  MASK = File.join ASSETS_FOLDER, "mask.fa"
  MASKED_DATABASE = File.join ASSETS_FOLDER, "masked_db.fa"
  MASK_POSNS = File.join ASSETS_FOLDER, "mask_posns.txt"
  MASK_NAMES = File.join ASSETS_FOLDER, "mask_names.txt"
end

Ryan.try_mkdir Const::ASSETS_FOLDER
