module Const
  WINDOW_SIZE = 300
  WINDOW_STEP = 25

  SILVA_LEN = 50000

  DATABASE = File.join "test_files", "database.fa"

  ASSETS_FOLDER = "assets"

  DE_DIST = File.join ASSETS_FOLDER, "database_DE_dist.txt"
  DE_DIST_PERCENTILES =
    File.join ASSETS_FOLDER, "database_DE_dist_percentiles.txt"

  NUM_PERCENTILES = 10

  RSCRIPT = File.join ASSETS_FOLDER, "pintail_plot.r"

  # not a user file, generated by the program
  FLAGGED_SEQS = File.join ASSETS_FOLDER, "queries.pintail_flagged.txt"
end

Ryan.try_mkdir Const::ASSETS_FOLDER
