module Const
  CLIBH = File.join File.dirname(__FILE__), "lib", "methods.h"

  WINDOW_SIZE = 100
  WINDOW_STEP = 10

  OTU_CUTOFF = 0.03

  SILVA_LEN = 50000

  ASSETS_FOLDER = File.join File.dirname(__FILE__), "assets"

  OUTGROUPS = File.join ASSETS_FOLDER, "outgroups.txt"

  ENTROPY = File.join ASSETS_FOLDER, "entropy.db_no_outgroups.txt"

  HV_REGIONS = File.join ASSETS_FOLDER, "hv_regions.txt"

  DATABASE = File.join ASSETS_FOLDER, "database.fa"

  if WINDOW_SIZE == 300 && WINDOW_STEP == 25
    DE_DIST = File.join ASSETS_FOLDER, "database_DE_dist.txt"
    DE_DIST_PERCENTILES =
      File.join ASSETS_FOLDER, "database_DE_dist_percentiles.txt"
  elsif WINDOW_SIZE == 100 && WINDOW_STEP == 10
    DE_DIST =
      File.join ASSETS_FOLDER,
                "10000_proteobacteria_window_100_step_10",
                "10000.proteobacteria.de_dist.txt.gz"
    DE_DIST_PERCENTILES =
      File.join ASSETS_FOLDER,
                "10000_proteobacteria_window_100_step_10",
                "10000.proteobacteria.de_dist.percentiles.txt"
  else
    abort "[WINDOW_SIZE, WINDOW_STEP] must be either [300, 25], " +
          "or [100, 10]; was [#{WINDOW_SIZE}, #{WINDOW_STEP}]"
  end


  NUM_PERCENTILES = 10

  RSCRIPT = File.join ASSETS_FOLDER, "pintail_plot.r"

  # not a user file, generated by the program
  FLAGGED_SEQS = File.join ASSETS_FOLDER, "queries.pintail_flagged.txt"

  MASK = File.join ASSETS_FOLDER, "mask.fa"
  MASKED_DATABASE = File.join ASSETS_FOLDER, "masked_db.fa"
  MASK_POSNS = File.join ASSETS_FOLDER, "mask_posns.txt"
  MASK_NAMES = File.join ASSETS_FOLDER, "mask_names.txt"
end

Ryan.try_mkdir Const::ASSETS_FOLDER

# check that the window size here matches that in the c headers
clibh = File.open(Const::CLIBH).read
unless clibh.include?("WINDOW_SIZE #{Const::WINDOW_SIZE}")
  abort "ERROR: WINDOW_SIZE in const.rb and lib/methods.h don't " +
        "match.\nAny changes require re-compiling."
end

unless clibh.include?("WINDOW_STEP #{Const::WINDOW_STEP}")
  abort "ERROR: WINDOW_STEP in const.rb and lib/methods.h don't " +
        "match.\nAny changes require re-compiling."
end
